version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://neondb_owner:npg_GwYa1XKMsEg6@ep-wild-rain-ai7hlqdz-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require"
      NEXTAUTH_SECRET: "super-secret-key-change-in-production-abc123"
      NEXTAUTH_URL: "http://localhost:3000"
      JWT_SECRET: "jwt-secret-key-change-in-production-xyz789"
      NEXT_PUBLIC_APP_URL: "http://localhost:3000"
    command: >
      sh -c "npx prisma db push && npx tsx prisma/seed.ts && npm start"
